# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/workspace/lupnp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/workspace/lupnp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/workspace/lupnp/CMakeFiles /home/pi/workspace/lupnp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/workspace/lupnp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lupnp

# Build rule for target.
lupnp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lupnp
.PHONY : lupnp

# fast build rule for target.
lupnp/fast:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/build
.PHONY : lupnp/fast

Source/HardwareHandler.o: Source/HardwareHandler.c.o
.PHONY : Source/HardwareHandler.o

# target to build an object file
Source/HardwareHandler.c.o:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/HardwareHandler.c.o
.PHONY : Source/HardwareHandler.c.o

Source/HardwareHandler.i: Source/HardwareHandler.c.i
.PHONY : Source/HardwareHandler.i

# target to preprocess a source file
Source/HardwareHandler.c.i:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/HardwareHandler.c.i
.PHONY : Source/HardwareHandler.c.i

Source/HardwareHandler.s: Source/HardwareHandler.c.s
.PHONY : Source/HardwareHandler.s

# target to generate assembly for a file
Source/HardwareHandler.c.s:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/HardwareHandler.c.s
.PHONY : Source/HardwareHandler.c.s

Source/UpnpCore.o: Source/UpnpCore.c.o
.PHONY : Source/UpnpCore.o

# target to build an object file
Source/UpnpCore.c.o:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/UpnpCore.c.o
.PHONY : Source/UpnpCore.c.o

Source/UpnpCore.i: Source/UpnpCore.c.i
.PHONY : Source/UpnpCore.i

# target to preprocess a source file
Source/UpnpCore.c.i:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/UpnpCore.c.i
.PHONY : Source/UpnpCore.c.i

Source/UpnpCore.s: Source/UpnpCore.c.s
.PHONY : Source/UpnpCore.s

# target to generate assembly for a file
Source/UpnpCore.c.s:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/UpnpCore.c.s
.PHONY : Source/UpnpCore.c.s

Source/main.o: Source/main.c.o
.PHONY : Source/main.o

# target to build an object file
Source/main.c.o:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/main.c.o
.PHONY : Source/main.c.o

Source/main.i: Source/main.c.i
.PHONY : Source/main.i

# target to preprocess a source file
Source/main.c.i:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/main.c.i
.PHONY : Source/main.c.i

Source/main.s: Source/main.c.s
.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.c.s:
	$(MAKE) -f CMakeFiles/lupnp.dir/build.make CMakeFiles/lupnp.dir/Source/main.c.s
.PHONY : Source/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lupnp"
	@echo "... rebuild_cache"
	@echo "... Source/HardwareHandler.o"
	@echo "... Source/HardwareHandler.i"
	@echo "... Source/HardwareHandler.s"
	@echo "... Source/UpnpCore.o"
	@echo "... Source/UpnpCore.i"
	@echo "... Source/UpnpCore.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

